### ISSUE TITLE
Write(string, string) - it writes only one line, so if you pass a JSON data, you don't write everything, if your JSON is formatted

### ISSUE THREAD

**Issue by danielkornev** [BobbyCannon/Speedy#1]
My suggestion is to highlight this thing in the Readme.md :)

**Comment by BobbyCannon** [comment]
Yep, I'm working on version 3 now that will support multi-line strings and also now generic types. Thank you so much for your feedback!

**Comment by BobbyCannon** [comment]
Fixed in version 3.
