### ISSUE TITLE
Limit of Items in Key Value Repository

### ISSUE THREAD

**Issue by vector-man** [BobbyCannon/Speedy#3]
Is there a limit to the number of items you can store in a Key Value Repository?

**Comment by BobbyCannon** [comment]
Technically no but there is the limit on file system. Also you should think about how fast you need the repository to be. In other words if you're running on FAT32 then the limit is 4GB. However if you have a 4GB repo then it's probably going to be pretty slow if you seek a lot. So it really depends on your file system and how you use the repository. 

Does that answer your question?

**Comment by BobbyCannon** [comment]
I'm very interested in your experience and what you think. Please let me know if you have any issues or if you have an comments / suggestions.
